schema = 1
name = "voris-vio"
display_name = "VIO"
version = "0.1.0-dev"
language = "C++23"
primary_target = "voris_vio"
include_prefix = "voris/io"

[[dependencies]]
name = "voris-vmem"
optional = false
